# Generated by Django 3.1.3 on 2020-11-25 21:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                (
                    'code',
                    models.CharField(
                        max_length=3,
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.RegexValidator(
                                code='invalid_length',
                                message='This value must be 3 characters long',
                                regex='^.{3}$',
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Bond',
            fields=[
                (
                    'isin',
                    models.CharField(
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                code='invalid_length',
                                message='This value must be 12 characters long',
                                regex='^.{12}$',
                            )
                        ],
                    ),
                ),
                ('size', models.BigIntegerField()),
                ('maturity', models.DateField()),
                (
                    'lei',
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.RegexValidator(
                                code='invalid_length',
                                message='This value must be 20 characters long',
                                regex='^.{20}$',
                            )
                        ],
                    ),
                ),
                ('legal_name', models.CharField(max_length=100)),
                (
                    'currency',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to='bonds.currency'
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='bonds',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
